service: appsync
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false
  # path: dist/apps/appsync
  custom:
    enable_optimize:
      local: false
provider:
  name: aws
  region: undefined
  endpointType: undefined
  runtime: nodejs10.x
functions:
  hello-world:
    handler: src/handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
      